version: "3.5"

services:
  api01: &api
    # image: ivmello/rinha-go-2024:latest
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
       - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    networks:
      - default
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./scripts/postgres/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "440MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-network