version: "3.5"

services:
  api01: &api
    hostname: api01
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/rinha?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"

  api02:
    <<: *api 
    hostname: api02
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
       - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=1000 -c shared_buffers=256MB -c synchronous_commit=off -c fsync=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-network